### ISSUE TITLE
WMS 1.1.1 test case failing for Transparency due to PNG

### ISSUE THREAD

**Issue by dineshahuja** [opengeospatial/ets-wms11#30] opened 2015-05-05 07:10 UTC
![ogc](https://cloud.githubusercontent.com/assets/696399/7468284/33d831e2-f324-11e4-823c-c1f6f3224acd.jpg)
We have been trying to run WMS 1.1.1 test cases on beta test engine http://cite.opengeospatial.org/te2.
There is one particular test " Test wms:wmsops-getmap-params-transparent-3" is failing which our product was passing earlier.
I have looked into the script code and could see that it is making a request for PNG format. Whereas earlier it used to execute this specific test case on gif format and our test case was  passing then but now it is failing.

**Comment by bermud** [comment] 2015-05-05 09:31
@segoerke, this issue might be related to #20. Please verify.

**Comment by dineshahuja** [comment] 2015-05-05 10:25
I believe code being executed in Case 30: is as follows

         <xsl:for-each select="$request1">
            <xsl:variable name="expression">xs:integer(//parsers:count) eq 0</xsl:variable>
            <xsl:if test="saxon:evaluate($expression)">
               <ctl:message>[FAILED] xs:integer(//parsers:count) eq 0 is true.</ctl:message>
               <ctl:message>Expected some pixels with an alpha value of 0 (fully transparent).</ctl:message>
               <fail/>
            </xsl:if>
         </xsl:for-each>

Whereas code being executed in case:20 is 
         <xsl:for-each select="$request1">
            <xsl:choose><xsl:when test="exists(//IHDR/@colorType[contains(.,'RGBAlpha')])">
                  <xsl:variable name="expression">xs:integer(//parsers:count) eq 0</xsl:variable>
                  <xsl:if test="saxon:evaluate($expression)">
                     <ctl:message>[FAILED] xs:integer(//parsers:count) eq 0 is true.</ctl:message>
                     <ctl:message>Expected some pixels with an alpha value of 0 (fully transparent).</ctl:message>
                     <fail/>
                  </xsl:if>
               </xsl:when>
               <xsl:when test="exists(//tRNS)">
                  <xsl:variable name="expression">((//tRNS/tRNS_RGB/@blue/text()) != '255') and ((//tRNS/tRNS_RGB/@green/text()) != '255') and ((//tRNS/tRNS_RGB/@red/text()) != '255')</xsl:variable>
                  <xsl:if test="saxon:evaluate($expression)">
                     <ctl:message>[FAILED] ((//tRNS/tRNS_RGB/@blue/text()) != '255') and ((//tRNS/tRNS_RGB/@green/text()) != '255') and ((//tRNS/tRNS_RGB/@red/text()) != '255') is true.</ctl:message>
                     <ctl:message>Expected some pixels with an alpha value of 0 (fully transparent).</ctl:message>
                     <fail/>
                  </xsl:if>
               </xsl:when>
               <xsl:otherwise>
                  <fail/>
               </xsl:otherwise>
            </xsl:choose>
         </xsl:for-each>

It seems both might be related but case 20 is passing and case 30 is failing for me.

**Comment by bermud** [comment] 2015-05-07 14:01
@segoerke please investigate !

**Comment by dineshahuja** [comment] 2015-05-15 07:02
Can i please get to know do we have any updates on this.

**Comment by segoerke** [comment] 2015-05-18 14:04
Just merged pull request which handles the issue (see #31)

**Comment by segoerke** [comment] 2015-05-20 14:42
For me the issue is not reproduceable neithter on beta, nor locally.

**Comment by bermud** [comment] 2015-06-10 13:37
It seems it was close with https://github.com/opengeospatial/ets-wms11/commit/72e7f9615daba8bebff537f330ffeb8de2d36617

**Closed by bermud** 2015-06-10 13:37 UTC
Labels: bug
